### PR TITLE
[Nexus] increase to 20.0.0

### PR DESCRIPTION
**Pull request by AlwinEsch**
Only version increase and build change

### CODE REVIEW

**Comment by rbuehlma** [comment]
I would prefer to have the Matrix branche merged into Nexus instead of creating the same changes here.

**Comment by AlwinEsch** [comment]
Yes would be better, as I'm also with rights can do a small cleanup on Nexus branch and make synchron to Matrix again and apply the change patch from you back.

**Comment by AlwinEsch** [comment]
Then on this request stays only the CI change and version increase.

**Comment by AlwinEsch** [comment]
The request is updated and has a rebase on Nexus branch with changes from Matrix.

**Comment by AlwinEsch** [comment]
NOT merge!!! Somethings missing on rebase!

**Comment by AlwinEsch** [comment]
Ok, now the Nexus branch correct and from here can in.

**Pull request merged**
