### PR TITLE
[Nexus] API related update

### PR DESCRIPTION
**Pull request by AlwinEsch**
This PR should be rebuilt after these xbmc PRs are merged:
- xbmc/xbmc#20705
- xbmc/xbmc#20710

The API changes on Kodi need be in.

### CODE REVIEW

**Comment by rbuehlma** [comment]
Why are all the tests failing? Is this something to worry about?

**Comment by AlwinEsch** [comment]
Kodi's requests are not in, by c&p was a bit wrong text in description.

**Comment by phunkyfish** [comment]
@rbuehlma this can now be merge and released, thanks!

Edit: fixed type from `not` -> `now`!

**Comment by rbuehlma** [comment]
Thanks. Release created.

**Pull request merged**
